<a href="https://colab.research.google.com/github/Takuya-hr/w2-horaguchi/blob/main/2%E5%80%A4%E5%88%86%E9%A1%9E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ２値分類

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import japanize_matplotlib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression as LR

In [ ]:
train = pd.read_csv('train.csv',engine='python')
test = pd.read_csv('test.csv',engine='python')
sample = pd.read_csv("submit_sample.csv",header=None)
sample.head()

0  1
0  0  0
1  1  0
2  2  0
3  3  0
4  4  0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# 予測の手がかりとなるカラムを取り出し、変数Xに代入
X = train[['duration','day','age','month','poutcome','job']]
# 予測対象となるカラムを取り出し、変数targetに代入
y = train['y']
X_test = test[['duration','day','age','month','poutcome','job']]

In [ ]:
X_dum = pd.get_dummies(X)
X_test_dum = pd.get_dummies(X_test)

In [ ]:
#学習データと評価データに分割
X_train, X_test, y_train, y_test = train_test_split(X_dum, y, random_state=40, stratify=y)

In [ ]:
# モデルの箱を準備
lr = LR()

In [ ]:
lr.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
pred = lr.predict(X_test)
print(pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]


In [ ]:
sample[1] = pred
sample.to_csv("submit1.csv",index=None,header=None)

ValueError: ignored

In [ ]:
# 実測値y_test,予測値predを使ってf1_scoreを計算
f_one = f1_score(y_test,pred)
print(f_one)

0.0


In [ ]:
# 実測値y_test,予測値predを使ってconfusion_matrixを作成
cm = confusion_matrix(y_test, pred)
print(cm)

[[361   1]
 [ 13   0]]


In [ ]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [ ]:
# X_testに対する予測の確率値を算出
pred_proba = lr.predict_proba(X_test)
# 確率値をDataFrameに変換して格納
proba_df = pd.DataFrame(pred_proba)
# 確率値の先頭5行を表示
print(proba_df.head())

          0         1
0  0.983401  0.016599
1  0.957117  0.042883
2  0.993215  0.006785
3  0.993900  0.006100
4  0.980668  0.019332


In [ ]:
# 変数y_testのChargedOffカラムにおける値の合計値を算出
df = pd.DataFrame(y_test)

In [ ]:
val1 = df['y'].sum()
print(val1)

13


In [ ]:
# 1である確率値を降順で並び替え
proba_desc = proba_df[1].sort_values(ascending = False)
# 変数y_testのChargedOffカラムの値が1であるデータ数と同じ行番号のデータを抜き出す
threshold = proba_desc.iloc[y]
print(threshold)

202    0.564469
202    0.564469
202    0.564469
202    0.564469
202    0.564469
         ...   
202    0.564469
202    0.564469
202    0.564469
202    0.564469
202    0.564469
Name: 1, Length: 1500, dtype: float64


In [ ]:
# 閾値以上であれば1を、それ以外の場合は0を返り値とする自作関数を作成
def classification(x):
    # 閾値以上であれば1を返す
    if x >= 0.30:
        return 1
    # それ以外の場合は0を返す
    else:
        return 0

In [ ]:
print( classification(0.0748) )
print( classification(0.0747) )

0
0


In [ ]:
# 変数proba_dfに新たなカラムclass_newを作り、proba_dfのカラム「1」に自作関数classificationを適用した結果を代入
proba_df['class_new'] = proba_df[1].apply(classification)

In [ ]:
print(proba_df.head())

          0         1  class_new
0  0.983401  0.016599          0
1  0.957117  0.042883          0
2  0.993215  0.006785          0
3  0.993900  0.006100          0
4  0.980668  0.019332          0


In [ ]:
print(proba_df['class_new'].value_counts())

0    370
1      5
Name: class_new, dtype: int64


In [ ]:
f_one_2 = f1_score(y_test,proba_df['class_new'])
print(f_one_2)

0.1111111111111111


In [ ]:
# 新たな閾値での分類結果
cm2 = confusion_matrix(y_test, proba_df['class_new'])
print(cm2)

[[358   4]
 [ 12   1]]


In [ ]:
#ダウンサンプリング
# 変数X_trainと変数y_trainを結合 axis1は横方向に結合
train = pd.concat([X_train, y_train], axis = 1)
print(train.shape)
print(X_train.shape)

(76, 30)
(76, 29)


In [ ]:
#データをランダムで取り出すにはsample関数
#行数だけを取り出し .shape[0]
# 完済のデータと貸し倒れのデータを別々の変数に代入
fp = train[ train['y'] == 0 ]
co = train[ train['y'] == 1 ]
print(co.shape[0])

38


In [ ]:
# 貸し倒れのデータ数と同じ数だけ完済のデータをランダムに取り出し
fp = fp.sample(n = co.shape[0] , random_state = 0)
print(fp.shape[0])

38


In [ ]:
# 完済のデータと貸し倒れのデータを縦結合
train = pd.concat([fp, co])
# 説明変数と目的変数をそれぞれ別の変数に代入
X_train = train.drop(columns = ['y'])
print(X_train.head())
y_train = train['y']
print(y_train.head())

     duration  day  age  ...  job_student  job_technician  job_unemployed
512       147   16   35  ...            0               0               0
919       146   20   29  ...            0               0               0
194       158   18   44  ...            0               0               0
482       258   20   30  ...            0               0               1
903        29   20   33  ...            0               0               0

[5 rows x 29 columns]
512    0
919    0
194    0
482    0
903    0
Name: y, dtype: int64


In [ ]:
# モデルの箱を作成
lr2 = LR()
lr2.fit(X_train, y_train)
pred2 = lr2.predict(X_test)
print(pred2)

[1 0 0 0 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 1 0
 1 1 0 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1
 0 1 0 1 1 0 1 1 1 1 0 0 1 0 1 1 1 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 1 0 1 1 1 1 1 0 0 0 1 0 0 0 1 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 0
 1 0 1 0 0 1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 0 1 0 1 1 0 0 1 0 0 1
 0 1 1 1 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 1 1 1 1 0 1 0 1 1 0 0 0 1 1 1 1 1 0
 1 1 0 1 0 1 1 0 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0 0 1 0 0 0 1 1 1 1 0 1 0 1 0
 1 0 1 1 0 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 1 0 1 1 1 0 0 1 1 0 0 0 0 1 0 1
 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 0 0 0 0 0
 0 0 0 0 0]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
f_one_3 = f1_score(y_test, pred2)
print(f_one_3)

0.1134020618556701


In [ ]:
# 混同行列の作成
cm3 = confusion_matrix(y_test, pred2)
# 混同行列の表示
print(cm3)

[[192 170]
 [  2  11]]


In [ ]:
pred2 = lr2.predict(X_test_dum)
print(pred2)

[1 0 0 ... 1 1 1]


In [ ]:
sample[1] = pred2
sample.to_csv("submit6.csv",index=None,header=None)

In [ ]:
# 線形回帰のインポート
from sklearn.linear_model import LinearRegression
# MSEのインポート
from sklearn.metrics import mean_squared_error

In [ ]:
lm = LinearRegression()
lm.fit(X_train, y_train)
pred1 = lm.predict(X_test_dum)

In [ ]:
sample[1] = pred1
sample.to_csv("submit4.csv",index=None,header=None)